### ISSUE TITLE
Chapter 4 - Licences - FR  - Correction orthographique

### ISSUE THREAD

**Issue by bpetetot** [zenika-open-source/open-source-white-paper#14]
Faire au moins 3 relectures / corrections:
- [x] Première relecture par @nicolas-trouin (#18)
- [x] Seconde relecture
- [ ] Troisième relecture

**Comment by nicolas-trouin** [comment]
Can I take this ?

**Comment by bpetetot** [comment]
Yes of course, thanks 👍

**Comment by nicolas-trouin** [comment]
> Yes of course, thanks 👍

I'm on it ! 😄

**Comment by bpetetot** [comment]
@nicolas-trouin Thanks for this first review (#18)

**Comment by mickaelalibert** [comment]
Working on the second review :smile:
