### ISSUE TITLE
Chapter 2 - Translate from English to French

### ISSUE THREAD

**Issue by bpetetot** [zenika-open-source/open-source-white-paper#19]
Translate to french the following chapter file: `en/02-preparing-your-project-being-open-sourced.md` in the `fr/` folder.

**Comment by geromegrignon** [comment]
working on it

**Comment by frinyvonnick** [comment]
It was already done in #22. Sorry @geromegrignon.

**Comment by geromegrignon** [comment]
saw it live with @bpetetot. I'm reviewing the PR then.
