### ISSUE TITLE
In readme, replace links of chapter 3 by the repository URL

### ISSUE THREAD

**Issue by bpetetot** [zenika-open-source/open-source-white-paper#41]
Replace the 3 links by the dedicated repository of the chapter :
https://github.com/zenika-open-source/promote-open-source-project

Here the links to remove :
![image](https://user-images.githubusercontent.com/516360/137361664-676e4f5c-a4e4-4301-807c-7160e608f7af.png)

**Comment by baratanurag** [comment]
I want to contribute

**Comment by bpetetot** [comment]
You're welcome, you can make the PR ^^ thx

**Comment by bpetetot** [comment]
Sorry but already done by someone : https://github.com/zenika-open-source/open-source-white-paper/pull/42
